=== wakystuf/ESG-Mod/Endless Space Competitive Mod/Schemas/Amplitude.Unity.Runtime.RuntimeModule.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Datatable" />
  <xs:element name="RuntimeModule" nillable="true" type="RuntimeModule" />
  <xs:complexType name="RuntimeModule">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="Title" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Description" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Author" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Homepage" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="PreviewImageFile" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="ReleaseNotes" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Tags" type="Tags" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Thumbnail" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Plugins" type="ArrayOfChoice1" />
    </xs:sequence>
    <xs:attribute name="Type" type="RuntimeModuleType" use="required" />
    <xs:attribute default="1.0" name="Version" type="xs:string" />
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="Tags">
    <xs:simpleContent>
      <xs:extension base="xs:string" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ArrayOfChoice1">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element minOccurs="0" maxOccurs="1" name="RegistryPlugin" type="RegistryPlugin" />
      <xs:element minOccurs="0" maxOccurs="1" name="LocalizationPlugin" type="LocalizationPlugin" />
      <xs:element minOccurs="0" maxOccurs="1" name="DatabasePlugin" type="DatabasePlugin" />
      <xs:element minOccurs="0" maxOccurs="1" name="AIPlugin" type="AIPlugin" />
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="RegistryPlugin">
    <xs:complexContent mixed="false">
      <xs:extension base="RuntimePlugin">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="FilePath" type="xs:string" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="RuntimePlugin">
    <xs:attribute default="0" name="Priority" type="xs:int" />
  </xs:complexType>
  <xs:complexType name="LocalizationPlugin">
    <xs:complexContent mixed="false">
      <xs:extension base="RuntimePlugin">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="Directory" type="xs:string" />
        </xs:sequence>
        <xs:attribute default="english" name="DefaultLanguage" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DatabasePlugin">
    <xs:complexContent mixed="false">
      <xs:extension base="RuntimePlugin">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="1" name="ExtraTypes" type="ArrayOfXmlExtraType" />
          <xs:element minOccurs="0" maxOccurs="unbounded" name="FilePath" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="Overrides" type="ArrayOfXmlAttributeOverride" />
        </xs:sequence>
        <xs:attribute name="DataType" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ArrayOfXmlExtraType">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="ExtraType" type="XmlExtraType" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="XmlExtraType">
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="DataType" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="ArrayOfXmlAttributeOverride">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Override" type="XmlAttributeOverride" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="XmlAttributeOverride">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="ExtraType" type="XmlExtraType" />
    </xs:sequence>
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="DataType" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="AIPlugin">
    <xs:complexContent mixed="false">
      <xs:extension base="RuntimePlugin">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="AssemblyPath" type="xs:string" />
        </xs:sequence>
        <xs:attribute default="Release" name="Configuration" type="Configuration" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:simpleType name="Configuration">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Release" />
      <xs:enumeration value="Debug" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="RuntimeModuleType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Standalone" />
      <xs:enumeration value="Conversion" />
      <xs:enumeration value="Extension" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== wakystuf/ESG-Mod/Endless Space Competitive Mod/ESCM-Beta.xml
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="Documentation/Schemas/Amplitude.Unity.Runtime.RuntimeModule.xsd">
  <RuntimeModule Name="ESCMBeta" Type="Extension" Version="1.3.0">
    <Title>ESG Competitive Balance Mod - Private Test</Title>
    <Description>This is the private test version for the ESG Mod. You're welcome to use this if you see it, but I'm not going to publically announce what we are testing.</Description>
    <Author>Endless Space Gaming</Author>
    <Homepage></Homepage>
    <PreviewImageFile>ModIcon.png</PreviewImageFile>
    <ReleaseNotes></ReleaseNotes>
    <Tags></Tags>
    <Plugins>
      <!-- Community Map - Last Updated v1.11
      > Academy       -> Academy AI related stuff
      > AllTheTraits  -> Merged all the traits mod
      > Documentation -> List of Plugins
      > GUI           -> Linking a simulation object, localization pair, (potentially) an image, and GUI object together
      > Hacking       -> Hacking outcome definitions
      > Localization  -> Translation pairs
      > Mapping       -> If this folder is here I screwed up
      > Quests        -> Quest Definitions
      > Settings      -> Things that mess with world / game settings
      > Simulation    -> Technologies, Balancing, System Improvements, Button Behaviors, System Improvements, Laws, Populations
      >> Battles      -> Hull / Ship Designs/Roles, Ship Stats, Module Stats
      Registry.xml    -> Max Faction Traits, More Market Purchases, Pirate Spawn Messing, Trade Company stuff, etc.
      ModIcon.png     -> It's the mod icon dummy, what do you think it is
      ESCM.xml        -> This is the main mod file, it sets the mod metadata and loads the plugins that deal with the mod contents
      -->
      <!-- Registry -->
      <RegistryPlugin>
        <FilePath>Registry.xml</FilePath>
      </RegistryPlugin>

      <!-- Galaxy Generation -->
      <DatabasePlugin DataType="GalaxyGeneratorWeightTableDefinition, Assembly-CSharp">
        <FilePath>Galaxy/WeightTableDefinitions.xml</FilePath>
      </DatabasePlugin>

      <!-- Game Settings -->
      <DatabasePlugin DataType="GameSettingDefinition, Assembly-CSharp">
        <ExtraTypes>
          <ExtraType DataType="WorldSettingDefinition, Assembly-CSharp" />
        </ExtraTypes>
        <FilePath>Settings/GameSettingDefinitions.xml</FilePath>
        <FilePath>Settings/WorldSettingDefinitions.xml</FilePath>
      </DatabasePlugin>

      <!-- Entity Actions -->
      <DatabasePlugin DataType="EntityActionDefinition, Assembly-CSharp">
        <ExtraTypes>
          <ExtraType DataType="EmpireDiplomacyGiveResourcesActionDefinition, Assembly-CSharp" />
          <ExtraType DataType="FireIonWaveFleetActionDefinition, Assembly-CSharp" />
          <ExtraType DataType="InitiateTerraformationEmpireActionFleetActionDefinition, Assembly-CSharp" />
          <ExtraType DataType="InitiateRestorationEmpireActionFleetActionDefinition, Assembly-CSharp" />
          <ExtraType DataType="InvisibilityFleetActionDefinition, Assembly-CSharp" />
        </ExtraTypes>
        <FilePath>Simulation/EntityActions.xml</FilePath>
      </DatabasePlugin>

      <!-- Diplomacy -->
      <DatabasePlugin DataType="ForeignAffairsConstructibleElement, Assembly-CSharp">
        <ExtraTypes>
          <ExtraType DataType="DiplomaticTermDefinition, Assembly-CSharp" />
          <ExtraType DataType="DiplomaticTermDiplomaticRelationStateDefinition, Assembly-CSharp" />
          <ExtraType DataType="DiplomaticTermResourceExchangeDefinition, Assembly-CSharp" />
          <ExtraType DataType="DiplomaticTermTechnologyExchangeDefinition, Assembly-CSharp" />
          <ExtraType DataType="DiplomaticTermStarSystemColonyExchangeDefinition, Assembly-CSharp" />
          <ExtraType DataType="DiplomaticTermStarSystemOutpostExchangeDefinition, Assembly-CSharp" />
          <ExtraType DataType="DiplomaticTermAllianceDefinition, Assembly-CSharp" />
          <ExtraType DataType="DiplomaticTermBreakAllianceDefinition, Assembly-CSharp" />
          <ExtraType DataType="DiplomaticTermProposalDefinition, Assembly-CSharp" />
          <ExtraType DataType="DiplomaticTermDeclareWarDefinition, Assembly-CSharp" />
          <ExtraType DataType="DiplomaticTermPressureReductionDefinition, Assembly-CSharp" />
          <ExtraType DataType="DiplomaticTermResourceExchangeDemandDefinition, Assembly-CSharp" />
          <ExtraType DataType="DiplomaticTermTechnologyExchangeDemandDefinition, Assembly-CSharp" />
          <ExtraType DataType="DiplomaticTermMapSharingDefinition, Assembly-CSharp" />
          <ExtraType DataType="DiplomaticTermPressureEffectDefinition, Assembly-CSharp" />
          <ExtraType DataType="DiplomaticTermPressureIncreaseDefinition, Assembly-CSharp" />
          <ExtraType DataType="DiplomaticTermFactionPactDefinition, Assembly-CSharp" />
          <ExtraType DataType="DiplomaticTermRenounceAllianceDefinition, Assembly-CSharp" />
        </ExtraTypes>
        <FilePath>Diplomacy/ForeignAffairsConstructibles.xml</FilePath>
        <FilePath>Diplomacy/ForeignAffairsConstructibles[*].xml</FilePath>
      </DatabasePlugin>

      <DatabasePlugin DataType="DiplomaticRelationState, Assembly-CSharp">
        <FilePath>Diplomacy/DiplomaticRelationStates.xml</FilePath>
        <FilePath>Diplomacy/DiplomaticRelationStates[*].xml</FilePath>
      </DatabasePlugin>
      
      <!-- Simulation -->
      <DatabasePlugin DataType="Amplitude.Unity.Simulation.SimulationDescriptor, Assembly-CSharp-firstpass">
        <FilePath>Simulation/SimulationDescriptors[*].xml</FilePath>
        <FilePath>Simulation/SimulationDescriptors.xml</FilePath>
        <FilePath>Simulation/Battles/SimulationDescriptors[*].xml</FilePath>
        <FilePath>Simulation/Battles/SimulationDescriptors.xml</FilePath>
        <FilePath>Simulation/Battles/Ground/SimulationDescriptors[*].xml</FilePath>
        <FilePath>Simulation/Battles/Ground/SimulationDescriptors.xml</FilePath>
        <FilePath>Simulation/Traits/SimulationDescriptors[*].xml</FilePath>
      </DatabasePlugin>

      <!-- Population -->
      <DatabasePlugin DataType="PopulationDefinition, Assembly-CSharp">
        <FilePath>Simulation/PopulationDefinitions.xml</FilePath>
        <FilePath>Simulation/PopulationDefinitions[*].xml</FilePath>
      </DatabasePlugin>

      <DatabasePlugin DataType="PopulationTrait, Assembly-CSharp">
        <ExtraTypes>
          <ExtraType DataType="PopulationCollectionBonusTrait, Assembly-CSharp"/>
          <ExtraType DataType="PopulationModifiersTrait, Assembly-CSharp"/>
        </ExtraTypes>
        <FilePath>Simulation/Traits/PopulationModifiersTraits[*].xml</FilePath>
        <FilePath>Simulation/PopulationCollectionBonusTraits.xml</FilePath>
        <FilePath>Simulation/PopulationCollectionBonusTraits[*].xml</FilePath>
      </DatabasePlugin>

      <DatabasePlugin DataType="PopulationCollectionBonusTrait, Assembly-CSharp">
        <FilePath>Simulation/PopulationCollectionBonusTraits.xml</FilePath>
      </DatabasePlugin>

      <DatabasePlugin DataType="PopulationModifiersTrait, Assembly-CSharp">
        <FilePath>Simulation/Traits/PopulationModifiersTraits[*].xml</FilePath>
      </DatabasePlugin>

      <!-- Ship Design, Ship Roll, Hulls -->
      <DatabasePlugin DataType="ShipDesignDefinition, Assembly-CSharp">
        <FilePath>Simulation/Battles/ShipDesignDefinitions.xml</FilePath>
        <FilePath>Simulation/Battles/ShipDesignDefinitions[*].xml</FilePath>
      </DatabasePlugin>

      <DatabasePlugin DataType="ShipRoleDefinition, Assembly-CSharp">
        <FilePath>Simulation/Battles/ShipRoleDefinitions[*].xml</FilePath>
      </DatabasePlugin>

      <DatabasePlugin DataType="HullDefinition, Assembly-CSharp">
        <FilePath>Simulation/Battles/HullDefinitions[*].xml</FilePath>
      </DatabasePlugin>

      <DatabasePlugin DataType="ModuleDefinition, Assembly-CSharp" Priority="10">
        <ExtraTypes>
          <ExtraType DataType="SupportModuleDefinition, Assembly-CSharp" />
          <ExtraType DataType="SquadronModuleDefinition, Assembly-CSharp" />
          <ExtraType DataType="SystemSupportModuleDefinition, Assembly-CSharp" />
          <ExtraType DataType="DestructionModuleDefinition, Assembly-CSharp" />
        </ExtraTypes>
        <FilePath>Simulation/Battles/ModuleDefinitions[*].xml</FilePath>
      </DatabasePlugin>

      <DatabasePlugin DataType="SquadronMissionDefinition, Assembly-CSharp">
        <FilePath>Simulation/Battles/Squadrons/SquadronMissionDefinitions.xml</FilePath>
      </DatabasePlugin>

      <!-- Senate -->
      <DatabasePlugin DataType="PoliticsDefinition, Assembly-CSharp">
        <FilePath>Simulation/PoliticsDefinitions.xml</FilePath>
      </DatabasePlugin>

      <DatabasePlugin DataType="LawDefinition, Assembly-CSharp">
        <FilePath>Simulation/LawDefinitions.xml</FilePath>
        <FilePath>Simulation/LawDefinitions[*].xml</FilePath>
      </DatabasePlugin>

      <!-- Heroes -->
      <DatabasePlugin DataType="HeroSkillTreeDefinition, Assembly-CSharp">
        <FilePath>Simulation/HeroSkillTreeDefinitions.xml</FilePath>
      </DatabasePlugin>

      <DatabasePlugin DataType="HeroClassDefinition, Assembly-CSharp">
        <FilePath>Simulation/HeroClassDefinitions.xml</FilePath>
      </DatabasePlugin>

      <DatabasePlugin DataType="HeroSkillDefinition, Assembly-CSharp">
        <FilePath>Simulation/HeroSkillDefinitions.xml</FilePath>
      </DatabasePlugin>
      
      <!-- Constructibles -->
      <DatabasePlugin DataType="IndustryConstructibleElement, Assembly-CSharp">
        <ExtraTypes>
          <ExtraType DataType="StarSystemImprovementDefinition, Assembly-CSharp" />
          <ExtraType DataType="PlanetImprovementDefinition, Assembly-CSharp" />
          <ExtraType DataType="PlanetTerraformationDefinition, Assembly-CSharp" />
