=== wakystuf/ESG-Mod/Endless Space Competitive Mod/Schemas/HeroDefinition.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Datatable" />
  <xs:element name="HeroDefinition" nillable="true" type="HeroDefinition" />
  <xs:complexType name="HeroDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="HeroSkillProviderDefinition">
        <xs:sequence>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element minOccurs="0" maxOccurs="1" name="StatisticPrerequisite" type="StatisticPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="DatePrerequisite" type="DatePrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="DownloadableContentPrerequisite" type="DownloadableContentPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="GameSettingPrerequisite" type="GameSettingPrerequisite" />
          </xs:choice>
          <xs:element minOccurs="0" maxOccurs="1" name="Affinity" type="XmlNamedReference" />
          <xs:element minOccurs="0" maxOccurs="1" name="Class" type="XmlNamedReference" />
          <xs:element minOccurs="0" maxOccurs="1" name="Politics" type="XmlNamedReference" />
          <xs:element minOccurs="0" maxOccurs="1" name="ShipDesign" type="XmlNamedReference" />
          <xs:element minOccurs="0" maxOccurs="unbounded" name="SkillTree" type="XmlNamedReference" />
          <xs:element minOccurs="0" maxOccurs="1" name="LevelUpRuleReference" type="XmlNamedReference" />
        </xs:sequence>
        <xs:attribute default="false" name="Hidden" type="xs:boolean" />
        <xs:attribute default="false" name="IgnoreInstanceNumber" type="xs:boolean" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="StatisticPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite">
        <xs:attribute default="-3.40282347E+38" name="MinimumValue" type="xs:float" />
        <xs:attribute default="3.40282347E+38" name="MaximumValue" type="xs:float" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="Prerequisite">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute default="false" name="Inverted" type="xs:boolean" />
        <xs:attribute name="Flags" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="DatePrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="DownloadableContentPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="GameSettingPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="XmlNamedReference">
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="HeroSkillProviderDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="DatatableElement">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="Skill" type="XmlNamedReference" />
          <xs:element minOccurs="0" maxOccurs="unbounded" name="SimulationDescriptorReference" type="SimulationDescriptorReference" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SimulationDescriptorReference">
    <xs:complexContent mixed="false">
      <xs:extension base="ValueType">
        <xs:attribute name="Name" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ValueType" />
  <xs:complexType name="DatatableElement">
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
</xs:schema>

=== wakystuf/ESG-Mod/Endless Space Competitive Mod/Simulation/HeroDefinitions.xml
<?xml version="1.0" encoding="utf-8" ?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Schemas/HeroDefinition.xsd">

  <!-- SOPHONS -->
  <!-- Fahemmn Nutharr -->
  <HeroDefinition Name="HeroSophons01">
    <Skill Name="HeroSkill01Sophons01"/>
    <Skill Name="HeroSkill02Sophons01"/>
    <Skill Name="HeroSkillInnateOverseer"/>

    <Affinity Name="HeroAffinitySophons"/>
    <Class Name="HeroClassAdministrator"/>
    <Politics Name="HeroPolitics01"/>

    <ShipDesign Name="ShipDesignHeroSmall04Defender"/>

    <SkillTree Name="HeroSkillTreeIndustrialist"/>
    <SkillTree Name="HeroSkillTreeSophons"/>
    <SkillTree Name="HeroSkillTreeAdministrator"/>

    <LevelUpRuleReference Name="HeroLevelUpRule"/>
  </HeroDefinition>

  <!-- Hanmharla Gerzi -->
    <HeroDefinition Name="HeroSophons02">
        <Skill Name="HeroSkill01Sophons02"/>
        <Skill Name="HeroSkill02Sophons02"/>

        <Affinity Name="HeroAffinitySophons"/>
        <Class Name="HeroClassAdventurer"/>
        <Politics Name="HeroPolitics05"/>

        <ShipDesign Name="ShipDesignHeroSmall02Explorer"/>

        <SkillTree Name="HeroSkillTreeReligious"/>
        <SkillTree Name="HeroSkillTreeSophons"/>
        <SkillTree Name="HeroSkillTreeAdventurer"/>

        <LevelUpRuleReference Name="HeroLevelUpRule"/>
    </HeroDefinition>	

  <!-- Uthassum Rhamoezz -->
  <HeroDefinition Name="HeroSophons03">
    <Skill Name="HeroSkill01Sophons03"/>
    <Skill Name="HeroSkill02Sophons03"/>
    <Skill Name="HeroSkillInnateCounselor"/>

    <Affinity Name="HeroAffinitySophons"/>
    <Class Name="HeroClassCorporate"/>
    <Politics Name="HeroPolitics03"/>

    <ShipDesign Name="ShipDesignHeroSmall03Supporter"/>

    <SkillTree Name="HeroSkillTreePacifist"/>
    <SkillTree Name="HeroSkillTreeSophons"/>
    <SkillTree Name="HeroSkillTreeCorporate"/>

    <LevelUpRuleReference Name="HeroLevelUpRule"/>
  </HeroDefinition>

  <!-- Asaroenni Dzulmaran (Starting hero) -->	
  <HeroDefinition Name="HeroSophons04">
    <Skill Name="HeroSkill01Sophons04"/>
    <Skill Name="HeroSkill02Sophons04"/>
    <Skill Name="HeroSkillInnateCounselor"/>

    <Affinity Name="HeroAffinitySophons"/>
    <Class Name="HeroClassCorporate"/>
    <Politics Name="HeroPolitics02"/>

    <ShipDesign Name="ShipDesignHeroSmall03Supporter"/>

    <SkillTree Name="HeroSkillTreeScientist"/>
    <SkillTree Name="HeroSkillTreeSophons"/>
    <SkillTree Name="HeroSkillTreeCorporate"/>
    <LevelUpRuleReference Name="HeroLevelUpRule"/>
  </HeroDefinition>

  <!-- 	Ahririnn Turlemmoz -->	
  <HeroDefinition Name="HeroSophons05">
    <Skill Name="HeroSkill01Sophons05"/>
    <Skill Name="HeroSkill02Sophons05"/>
    <Skill Name="HeroSkillInnateCounselor"/>

    <Affinity Name="HeroAffinitySophons"/>
    <Class Name="HeroClassCorporate"/>
    <Politics Name="HeroPolitics04"/>

    <ShipDesign Name="ShipDesignHeroSmall03Supporter"/>

    <SkillTree Name="HeroSkillTreeEcologist"/>
    <SkillTree Name="HeroSkillTreeSophons"/>
    <SkillTree Name="HeroSkillTreeCorporate"/>
    <LevelUpRuleReference Name="HeroLevelUpRule"/>
  </HeroDefinition>

  <!-- United Empire -->
  <!-- Immah Naratya -->
  <HeroDefinition Name="HeroTerrans01">
    <Skill Name="HeroSkill01Terrans01"/>
    <Skill Name="HeroSkill02Terrans01"/>
    <Skill Name="HeroSkillInnateOverseer"/>

    <Affinity Name="HeroAffinityTerrans"/>
    <Class Name="HeroClassAdministrator"/>
    <Politics Name="HeroPolitics04"/>

    <ShipDesign Name="ShipDesignHeroSmall04Defender"/>

    <SkillTree Name="HeroSkillTreeEcologist"/>
    <SkillTree Name="HeroSkillTreeTerrans"/>
    <SkillTree Name="HeroSkillTreeAdministrator"/>
    <LevelUpRuleReference Name="HeroLevelUpRule"/>
  </HeroDefinition>

  <!-- 	Dominik Havanen -->
  <HeroDefinition Name="HeroTerrans02">
    <Skill Name="HeroSkill01Terrans02"/>
    <Skill Name="HeroSkill02Terrans02"/>
    <Skill Name="HeroSkillInnateOverseer"/>

    <Affinity Name="HeroAffinityTerrans"/>
    <Class Name="HeroClassAdministrator"/>
    <Politics Name="HeroPolitics06"/>

    <ShipDesign Name="ShipDesignHeroSmall04Defender"/>

    <SkillTree Name="HeroSkillTreeMilitarist"/>
    <SkillTree Name="HeroSkillTreeTerrans"/>
    <SkillTree Name="HeroSkillTreeAdministrator"/>
    <LevelUpRuleReference Name="HeroLevelUpRule"/>
  </HeroDefinition>

  <!-- 	Oleg Lagarin -->	
    <HeroDefinition Name="HeroTerrans03">
        <Skill Name="HeroSkill01Terrans03"/>
        <Skill Name="HeroSkill02Terrans03"/>

        <Affinity Name="HeroAffinityTerrans"/>
        <Class Name="HeroClassAdmiral"/>
        <Politics Name="HeroPolitics02"/>

        <ShipDesign Name="ShipDesignHeroSmall01Attacker"/>

        <SkillTree Name="HeroSkillTreeScientist"/>
        <SkillTree Name="HeroSkillTreeTerrans"/>
        <SkillTree Name="HeroSkillTreeAdmiral"/>
        <LevelUpRuleReference Name="HeroLevelUpRule"/>
    </HeroDefinition>	
	
  <!-- 	Dmitri Lenko (Starting hero) -->	
  <HeroDefinition Name="HeroTerrans04">
    <Skill Name="HeroSkill01Terrans04"/>
    <Skill Name="HeroSkill02Terrans04"/>
    <Skill Name="HeroSkillInnateCounselor"/>

    <Affinity Name="HeroAffinityTerrans"/>
    <Class Name="HeroClassCorporate"/>
    <Politics Name="HeroPolitics01"/>

    <ShipDesign Name="ShipDesignHeroSmall03Supporter_Slow"/>

    <SkillTree Name="HeroSkillTreeIndustrialist"/>
    <SkillTree Name="HeroSkillTreeTerrans"/>
    <SkillTree Name="HeroSkillTreeCorporate"/>
    <LevelUpRuleReference Name="HeroLevelUpRule"/>
  </HeroDefinition>

  <!-- Kinete Muldaur -->	
    <HeroDefinition Name="HeroTerrans05">
		<Skill Name="HeroSkill01Terrans05"/>
        <Skill Name="HeroSkill02Terrans05"/>

        <Affinity Name="HeroAffinityTerrans"/>
        <Class Name="HeroClassAdmiral"/>
        <Politics Name="HeroPolitics05"/>

        <ShipDesign Name="ShipDesignHeroSmall01Attacker"/>

        <SkillTree Name="HeroSkillTreeReligious"/>
        <SkillTree Name="HeroSkillTreeTerrans"/>
        <SkillTree Name="HeroSkillTreeAdmiral"/>
        <LevelUpRuleReference Name="HeroLevelUpRule"/>
    </HeroDefinition>	
	
  <!-- 	Hadri Lenko -->	
    <HeroDefinition Name="HeroTerransQuest01" Hidden="true">
        <Skill Name="HeroSkill01TerransQuest01"/>
        <Skill Name="HeroSkill02TerransQuest01"/>

        <Affinity Name="HeroAffinityTerrans"/>
        <Class Name="HeroClassAdmiral"/>
        <Politics Name="HeroPolitics06"/>

        <ShipDesign Name="ShipDesignHeroSmall01Attacker"/>

        <SkillTree Name="HeroSkillTreeMilitarist"/>
        <SkillTree Name="HeroSkillTreeTerrans"/>
        <SkillTree Name="HeroSkillTreeAdmiral"/>
        <LevelUpRuleReference Name="HeroLevelUpRule"/>
    </HeroDefinition>	
	
  <!-- Lena Zelevas -->	
  <HeroDefinition Name="HeroTerransQuest02" Hidden="true">
    <Skill Name="HeroSkill01TerransQuest02"/>
    <Skill Name="HeroSkill02TerransQuest02"/>
    <Skill Name="HeroSkillInnateCounselor"/>

    <Affinity Name="HeroAffinityTerrans"/>
    <Class Name="HeroClassCorporate"/>
    <Politics Name="HeroPolitics05"/>

    <ShipDesign Name="ShipDesignHeroSmall03Supporter"/>

    <SkillTree Name="HeroSkillTreeReligious"/>
    <SkillTree Name="HeroSkillTreeTerrans"/>
    <SkillTree Name="HeroSkillTreeCorporate"/>
    <LevelUpRuleReference Name="HeroLevelUpRule"/>
  </HeroDefinition>

  <!-- Petra Mandzukic -->	
    <HeroDefinition Name="HeroTerransQuest03" Hidden="true">
        <Skill Name="HeroSkill01TerransQuest03"/>
        <Skill Name="HeroSkill02TerransQuest03"/>

        <Affinity Name="HeroAffinityTerrans"/>
        <Class Name="HeroClassAdventurer"/>
        <Politics Name="HeroPolitics02"/>

        <ShipDesign Name="ShipDesignHeroSmall02Explorer"/>

        <SkillTree Name="HeroSkillTreeScientist"/>
        <SkillTree Name="HeroSkillTreeTerrans"/>
        <SkillTree Name="HeroSkillTreeAdventurer"/>
        <LevelUpRuleReference Name="HeroLevelUpRule"/>
    </HeroDefinition>	
	
  <!-- HORATIO -->
  <!-- 	Farella -EM8 Mario 22 (Starting hero) -->
  <HeroDefinition Name="HeroHoratio01">
    <Skill Name="HeroSkill01Horatio01"/>
    <Skill Name="HeroSkill02Horatio01"/>
    <Skill Name="HeroSkillInnateOverseer"/>

    <Affinity Name="HeroAffinityHoratio"/>
    <Class Name="HeroClassAdministrator"/>
    <Politics Name="HeroPolitics04"/>

    <ShipDesign Name="ShipDesignHeroSmall04Defender"/>

    <SkillTree Name="HeroSkillTreeEcologist"/>
    <SkillTree Name="HeroSkillTreeHoratio"/>
    <SkillTree Name="HeroSkillTreeAdministrator"/>
    <LevelUpRuleReference Name="HeroLevelUpRule"/>
  </HeroDefinition>

  <!-- Andro Camille -Z -->	
	<HeroDefinition Name="HeroHoratio02">
		<Skill Name="HeroSkill01Horatio02"/>
		<Skill Name="HeroSkill02Horatio02"/>
		
		<Affinity Name="HeroAffinityHoratio"/>
		<Class Name="HeroClassAdventurer"/>
		<Politics Name="HeroPolitics02"/>

		<ShipDesign Name="ShipDesignHeroSmall02Explorer"/>

		<SkillTree Name="HeroSkillTreeScientist"/>
		<SkillTree Name="HeroSkillTreeHoratio"/>
		<SkillTree Name="HeroSkillTreeAdventurer"/>
		<LevelUpRuleReference Name="HeroLevelUpRule"/>
	</HeroDefinition>	
	
  <!-- Salario Domus -63 -->	
  <HeroDefinition Name="HeroHoratio03">
    <Skill Name="HeroSkill01Horatio03"/>
    <Skill Name="HeroSkill02Horatio03"/>
    <Skill Name="HeroSkillInnateCounselor"/>

    <Affinity Name="HeroAffinityHoratio"/>
    <Class Name="HeroClassCorporate"/>
    <Politics Name="HeroPolitics06"/>

    <ShipDesign Name="ShipDesignHeroSmall03Supporter"/>

    <SkillTree Name="HeroSkillTreeMilitarist"/>
    <SkillTree Name="HeroSkillTreeHoratio"/>
    <SkillTree Name="HeroSkillTreeCorporate"/>
    <LevelUpRuleReference Name="HeroLevelUpRule"/>
  </HeroDefinition>

  <!-- Ruthian -F11 Tighina -->	
  <HeroDefinition Name="HeroHoratio04">
    <Skill Name="HeroSkill01Horatio04"/>
    <Skill Name="HeroSkill02Horatio04"/>
    <Skill Name="HeroSkillInnateCounselor"/>

    <Affinity Name="HeroAffinityHoratio"/>
