=== wakystuf/ESG-Mod/Endless Space Competitive Mod/Schemas/MinorStateDefinition.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Datatable" />
  <xs:element name="MinorStateDefinition" nillable="true" type="MinorStateDefinition" />
  <xs:complexType name="MinorStateDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="DatatableElement">
        <xs:sequence>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element minOccurs="0" maxOccurs="1" name="DatePrerequisite" type="DatePrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="GameSettingPrerequisite" type="GameSettingPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="PathPrerequisite" type="PathPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="InterpreterPrerequisite" type="InterpreterPrerequisite" />
          </xs:choice>
          <xs:element minOccurs="0" maxOccurs="1" name="DefaultFleetMissionReference" type="XmlNamedReference" />
          <xs:element minOccurs="0" maxOccurs="1" name="FleetMissions" type="ArrayOfMinorStateFleetMissionDefinition" />
          <xs:element minOccurs="0" maxOccurs="unbounded" name="SimulationDescriptorReference" type="SimulationDescriptorReference" />
        </xs:sequence>
        <xs:attribute name="MinimumStress" type="xs:float" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DatePrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="Prerequisite">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute default="false" name="Inverted" type="xs:boolean" />
        <xs:attribute name="Flags" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="GameSettingPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="PathPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="InterpreterPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="XmlNamedReference">
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="ArrayOfMinorStateFleetMissionDefinition">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="FleetMission" type="MinorStateFleetMissionDefinition" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="MinorStateFleetMissionDefinition">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="FleetMissionReference" type="XmlNamedReference" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="FleetComposition" type="MinorStateFleetCompositionItem" />
    </xs:sequence>
    <xs:attribute name="Weight" type="xs:int" use="required" />
  </xs:complexType>
  <xs:complexType name="MinorStateFleetCompositionItem">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="1" name="DatePrerequisite" type="DatePrerequisite" />
        <xs:element minOccurs="0" maxOccurs="1" name="GameSettingPrerequisite" type="GameSettingPrerequisite" />
        <xs:element minOccurs="0" maxOccurs="1" name="PathPrerequisite" type="PathPrerequisite" />
        <xs:element minOccurs="0" maxOccurs="1" name="InterpreterPrerequisite" type="InterpreterPrerequisite" />
      </xs:choice>
      <xs:element minOccurs="0" maxOccurs="1" name="NeededShips" type="ArrayOfXmlNamedReference" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfXmlNamedReference">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="ShipDesign" type="XmlNamedReference" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SimulationDescriptorReference">
    <xs:complexContent mixed="false">
      <xs:extension base="ValueType">
        <xs:attribute name="Name" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ValueType" />
  <xs:complexType name="DatatableElement">
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
</xs:schema>

=== wakystuf/ESG-Mod/Endless Space Competitive Mod/Simulation/MinorStateDefinitions.xml
<?xml version="1.0" encoding="utf-8" ?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Schemas/MinorStateDefinition.xsd">

    <!--TODO: OVERALL: change Pirates ship to corresponding faction ships-->
    <!--TODO: add granularity to each MF family in fleet mission composition-->
    
    <!-- ######################################################################## -->
    <!-- #################### NON WARMONGER MINOR FACTIONS     ################## -->
    <!-- ######################################################################## -->     
    
    <!--Pacifists, Idle on Systems-->
    <!--State 1-->
    <MinorStateDefinition Name="InactivePacifist" MinimumStress="0">
        <PathPrerequisite Flags="Prerequisite">PersonalityTraitPacifist</PathPrerequisite>
        <FleetMissions>
            <FleetMission Weight="1">
                <!--Defend Mission-->
                <FleetMissionReference Name="DefendSystemIdle"/>
                <!--Pirates-->
                <FleetComposition>
                    <PathPrerequisite Flags="Prerequisite">FamilyPirates,MinorFactionDifficultyEasy</PathPrerequisite>
                    <NeededShips>
                        <ShipDesign Name="MinorFactionScavengerSmallAttackWeak"/>
                    </NeededShips>
                </FleetComposition>
                <FleetComposition>
                    <PathPrerequisite Flags="Prerequisite">FamilyPirates,MinorFactionDifficultyNormal</PathPrerequisite>
                    <NeededShips>
                        <ShipDesign Name="MinorFactionScavengerSmallAttackWeak"/>
                        <ShipDesign Name="MinorFactionScavengerSmallAttackWeak"/>
                    </NeededShips>
                </FleetComposition>
                <FleetComposition>
                    <PathPrerequisite Flags="Prerequisite">FamilyPirates,MinorFactionDifficultyHard</PathPrerequisite>
                    <NeededShips>
                        <ShipDesign Name="MinorFactionScavengerSmallAttackWeak"/>
                        <ShipDesign Name="MinorFactionScavengerSmallAttackAvg"/>
                        <ShipDesign Name="MinorFactionScavengerSmallAttackAvg"/>
                    </NeededShips>
                </FleetComposition>
                <!--Insectoids-->
                <FleetComposition>
                    <PathPrerequisite Flags="Prerequisite">FamilyInsectoids,MinorFactionDifficultyEasy</PathPrerequisite>
                    <NeededShips>
                        <ShipDesign Name="MinorFactionInsectoidSmallAttackWeak"/>
                    </NeededShips>
                </FleetComposition>
                <FleetComposition>
                    <PathPrerequisite Flags="Prerequisite">FamilyInsectoids,MinorFactionDifficultyNormal</PathPrerequisite>
                    <NeededShips>
                        <ShipDesign Name="MinorFactionInsectoidSmallAttackWeak"/>
                        <ShipDesign Name="MinorFactionInsectoidSmallAttackWeak"/>
                    </NeededShips>
                </FleetComposition>
                <FleetComposition>
                    <PathPrerequisite Flags="Prerequisite">FamilyInsectoids,MinorFactionDifficultyHard</PathPrerequisite>
                    <NeededShips>
                        <ShipDesign Name="MinorFactionInsectoidSmallAttackWeak"/>
                        <ShipDesign Name="MinorFactionInsectoidSmallAttackAvg"/>
                        <ShipDesign Name="MinorFactionInsectoidSmallAttackAvg"/>
                    </NeededShips>
                </FleetComposition>
                <!--Primitive-->
                <FleetComposition>
                    <PathPrerequisite Flags="Prerequisite">FamilyPrimitives,MinorFactionDifficultyEasy</PathPrerequisite>
                    <NeededShips>
                        <ShipDesign Name="MinorFactionPrimitiveSmallAttackWeak"/>
                    </NeededShips>
                </FleetComposition>
                <FleetComposition>
                    <PathPrerequisite Flags="Prerequisite">FamilyPrimitives,MinorFactionDifficultyNormal</PathPrerequisite>
                    <NeededShips>
                        <ShipDesign Name="MinorFactionPrimitiveSmallAttackWeak"/>
                        <ShipDesign Name="MinorFactionPrimitiveSmallAttackWeak"/>
                    </NeededShips>
                </FleetComposition>
                <FleetComposition>
                    <PathPrerequisite Flags="Prerequisite">FamilyPrimitives,MinorFactionDifficultyHard</PathPrerequisite>
                    <NeededShips>
                        <ShipDesign Name="MinorFactionPrimitiveSmallAttackWeak"/>
                        <ShipDesign Name="MinorFactionPrimitiveSmallAttackAvg"/>
                        <ShipDesign Name="MinorFactionPrimitiveSmallAttackAvg"/>
                    </NeededShips>
                </FleetComposition>
                <!--Advanced-->
                <FleetComposition>
                    <PathPrerequisite Flags="Prerequisite">FamilyAdvanced,MinorFactionDifficultyEasy</PathPrerequisite>
                    <NeededShips>
                        <ShipDesign Name="MinorFactionAdvancedSmallAttackWeak"/>
                    </NeededShips>
                </FleetComposition>
                <FleetComposition>
                    <PathPrerequisite Flags="Prerequisite">FamilyAdvanced,MinorFactionDifficultyNormal</PathPrerequisite>
                    <NeededShips>
                        <ShipDesign Name="MinorFactionAdvancedSmallAttackWeak"/>
                        <ShipDesign Name="MinorFactionAdvancedSmallAttackWeak"/>
                    </NeededShips>
                </FleetComposition>
                <FleetComposition>
                    <PathPrerequisite Flags="Prerequisite">FamilyAdvanced,MinorFactionDifficultyHard</PathPrerequisite>
                    <NeededShips>
                        <ShipDesign Name="MinorFactionAdvancedSmallAttackWeak"/>
                        <ShipDesign Name="MinorFactionAdvancedSmallAttackAvg"/>
                        <ShipDesign Name="MinorFactionAdvancedSmallAttackAvg"/>
                    </NeededShips>
                </FleetComposition>
            </FleetMission>
        </FleetMissions>
        <SimulationDescriptorReference Name="MinorResourceDistributionInactive"/>
    </MinorStateDefinition>
    <!--State 2-->
    <MinorStateDefinition Name="PassivePacifist" MinimumStress="7">
        <PathPrerequisite Flags="Prerequisite">PersonalityTraitPacifist</PathPrerequisite>
        <DefaultFleetMissionReference Name="DefendSystemIdle"/>
        <FleetMissions>
          <FleetMission Weight="1">
                <!--Defend Mission-->
                <FleetMissionReference Name="DefendSystemIdle"/>
                <!--Pirates-->
                <FleetComposition>
                  <PathPrerequisite Flags="Prerequisite">FamilyPirates,MinorFactionDifficultyEasy</PathPrerequisite>
                  <NeededShips>
                      <ShipDesign Name="MinorFactionScavengerSmallAttackWeak"/>
                  </NeededShips>
              </FleetComposition>
                <FleetComposition>
                    <PathPrerequisite Flags="Prerequisite">FamilyPirates,MinorFactionDifficultyNormal</PathPrerequisite>
                    <NeededShips>
                        <ShipDesign Name="MinorFactionScavengerSmallAttackWeak"/>
                        <ShipDesign Name="MinorFactionScavengerSmallAttackWeak"/>
                    </NeededShips>
                </FleetComposition>
                <FleetComposition>
                    <PathPrerequisite Flags="Prerequisite">FamilyPirates,MinorFactionDifficultyHard</PathPrerequisite>
                    <NeededShips>
                        <ShipDesign Name="MinorFactionScavengerSmallAttackWeak"/>
                        <ShipDesign Name="MinorFactionScavengerSmallAttackWeak"/>
                        <ShipDesign Name="MinorFactionScavengerSmallAttackAvg"/>
                        <ShipDesign Name="MinorFactionScavengerSmallAttackAvg"/>
                    </NeededShips>
                </FleetComposition>
                <!--Insectoids-->
                <FleetComposition>
                    <PathPrerequisite Flags="Prerequisite">FamilyInsectoids,MinorFactionDifficultyEasy</PathPrerequisite>
                    <NeededShips>
                        <ShipDesign Name="MinorFactionInsectoidSmallAttackWeak"/>
                    </NeededShips>
                </FleetComposition>
                <FleetComposition>
                  <PathPrerequisite Flags="Prerequisite">FamilyInsectoids,MinorFactionDifficultyNormal</PathPrerequisite>
                  <NeededShips>
                      <ShipDesign Name="MinorFactionInsectoidSmallAttackWeak"/>
                      <ShipDesign Name="MinorFactionInsectoidSmallAttackWeak"/>
                  </NeededShips>
                </FleetComposition>
                <FleetComposition>
                    <PathPrerequisite Flags="Prerequisite">FamilyInsectoids,MinorFactionDifficultyHard</PathPrerequisite>
                    <NeededShips>
                        <ShipDesign Name="MinorFactionInsectoidSmallAttackWeak"/>
                        <ShipDesign Name="MinorFactionInsectoidSmallAttackWeak"/>
                        <ShipDesign Name="MinorFactionInsectoidSmallAttackAvg"/>
                        <ShipDesign Name="MinorFactionInsectoidSmallAttackAvg"/>
                    </NeededShips>
                </FleetComposition>
                <!--Primitive-->
                <FleetComposition>
                    <PathPrerequisite Flags="Prerequisite">FamilyPrimitives,MinorFactionDifficultyEasy</PathPrerequisite>
                    <NeededShips>
                        <ShipDesign Name="MinorFactionPrimitiveSmallAttackWeak"/>
                    </NeededShips>
                </FleetComposition>
                <FleetComposition>
