=== wakystuf/ESG-Mod/Endless Space Competitive Mod/Schemas/TechnologyLinkDefinition.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Datatable" />
  <xs:element name="TechnologyLinkDefinition" nillable="true" type="TechnologyLinkDefinition" />
  <xs:complexType name="TechnologyLinkDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="DatatableElement">
        <xs:sequence>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element minOccurs="0" maxOccurs="1" name="DatePrerequisite" type="DatePrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="GameSettingPrerequisite" type="GameSettingPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="TechnologyPrerequisite" type="TechnologyPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="InterpreterPrerequisite" type="InterpreterPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="PathPrerequisite" type="PathPrerequisite" />
          </xs:choice>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="SimulationDescriptorReference" type="SimulationDescriptorReference" />
        </xs:sequence>
        <xs:attribute name="Category" type="xs:string" />
        <xs:attribute default="AND" name="PrerequisiteResolution" type="PrerequisiteResolutionType" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DatePrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="Prerequisite">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute default="false" name="Inverted" type="xs:boolean" />
        <xs:attribute name="Flags" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="GameSettingPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="PathValidityPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="TechnologyPrerequisite">
    <xs:simpleContent>
      <xs:extension base="PathValidityPrerequisite">
        <xs:attribute default="false" name="UnlockHidden" type="xs:boolean" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="InterpreterPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="PathPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="SimulationDescriptorReference">
    <xs:complexContent mixed="false">
      <xs:extension base="ValueType">
        <xs:attribute name="Name" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ValueType" />
  <xs:simpleType name="PrerequisiteResolutionType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="AND" />
      <xs:enumeration value="OR" />
      <xs:enumeration value="XOR" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="DatatableElement">
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
  <xs:element name="InteractiveTechnologyLinkDefinition" nillable="true" type="InteractiveTechnologyLinkDefinition" />
  <xs:complexType name="InteractiveTechnologyLinkDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="TechnologyLinkDefinition">
        <xs:sequence>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element minOccurs="0" maxOccurs="1" name="CustomCost" type="CustomConstructionCost" />
            <xs:element minOccurs="0" maxOccurs="1" name="Cost" type="ConstructionCost" />
          </xs:choice>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="CustomConstructionCost">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute default="false" name="Instant" type="xs:boolean" />
        <xs:attribute default="false" name="InstantOnCompletion" type="xs:boolean" />
        <xs:attribute name="ResourceName" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ConstructionCost">
    <xs:simpleContent>
      <xs:extension base="xs:float">
        <xs:attribute default="false" name="Instant" type="xs:boolean" />
        <xs:attribute default="false" name="InstantOnCompletion" type="xs:boolean" />
        <xs:attribute name="ResourceName" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== wakystuf/ESG-Mod/Endless Space Competitive Mod/Simulation/TechnologyLinkDefinitions.xml
<?xml version="1.0" encoding="utf-8" ?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Schemas/TechnologyLinkDefinition.xsd">
	<!-- Common -->
	<TechnologyLinkDefinition Name="TechnologyLinkDefinitionScienceAndExploration2To4CommonWormholeUnique" Category="TechnologyLinkTypeCostReduction" PrerequisiteResolution="OR">
		<TechnologyPrerequisite Flags="TechnologyLinkAvailability">TechnologyColonization2Common</TechnologyPrerequisite>
		<TechnologyPrerequisite Flags="TechnologyLinkAvailability">TechnologyWormholeCommonUnique</TechnologyPrerequisite>
		<SimulationDescriptorReference Name="TechnologyLinkScienceAndExploration2To4"/>
	</TechnologyLinkDefinition>

	<TechnologyLinkDefinition Name="TechnologyLinkDefinitionScienceAndExploration2To4CommonWormhole" Category="TechnologyLinkTypeCostReduction" PrerequisiteResolution="OR">
		<TechnologyPrerequisite Flags="TechnologyLinkAvailability">TechnologyColonization2Common</TechnologyPrerequisite>
		<TechnologyPrerequisite Flags="TechnologyLinkAvailability">TechnologyWormholeCommon</TechnologyPrerequisite>
		<SimulationDescriptorReference Name="TechnologyLinkScienceAndExploration2To4"/>
	</TechnologyLinkDefinition>

	<!-- Unfallen -->
	<TechnologyLinkDefinition Name="TechnologyLinkDefinitionScienceAndExploration2To4UnfallenWormholeUnique" Category="TechnologyLinkTypeCostReduction" PrerequisiteResolution="OR">
		<TechnologyPrerequisite Flags="TechnologyLinkAvailability">TechnologyColonization2Unfallen</TechnologyPrerequisite>
		<TechnologyPrerequisite Flags="TechnologyLinkAvailability">TechnologyWormholeUnfallenCommonUnique</TechnologyPrerequisite>
		<SimulationDescriptorReference Name="TechnologyLinkScienceAndExploration2To4"/>
	</TechnologyLinkDefinition>

	<TechnologyLinkDefinition Name="TechnologyLinkDefinitionScienceAndExploration2To4UnfallenWormhole" Category="TechnologyLinkTypeCostReduction" PrerequisiteResolution="OR">
		<TechnologyPrerequisite Flags="TechnologyLinkAvailability">TechnologyColonization2Unfallen</TechnologyPrerequisite>
		<TechnologyPrerequisite Flags="TechnologyLinkAvailability">TechnologyWormholeUnfallenCommon</TechnologyPrerequisite>
		<SimulationDescriptorReference Name="TechnologyLinkScienceAndExploration2To4"/>
	</TechnologyLinkDefinition>

	<!-- Riftborn -->
	<TechnologyLinkDefinition Name="TechnologyLinkDefinitionScienceAndExploration2To4TimeLordsWormholeUnique" Category="TechnologyLinkTypeCostReduction" PrerequisiteResolution="OR">
		<TechnologyPrerequisite Flags="TechnologyLinkAvailability">TechnologyColonization2TimeLords</TechnologyPrerequisite>
		<TechnologyPrerequisite Flags="TechnologyLinkAvailability">TechnologyWormholeTimeLordsCommonUnique</TechnologyPrerequisite>
		<SimulationDescriptorReference Name="TechnologyLinkScienceAndExploration2To4"/>
	</TechnologyLinkDefinition>

	<TechnologyLinkDefinition Name="TechnologyLinkDefinitionScienceAndExploration2To4TimeLordsWormhole" Category="TechnologyLinkTypeCostReduction" PrerequisiteResolution="OR">
		<TechnologyPrerequisite Flags="TechnologyLinkAvailability">TechnologyColonization2TimeLords</TechnologyPrerequisite>
		<TechnologyPrerequisite Flags="TechnologyLinkAvailability">TechnologyWormholeTimeLordsCommon</TechnologyPrerequisite>
		<SimulationDescriptorReference Name="TechnologyLinkScienceAndExploration2To4"/>
	</TechnologyLinkDefinition>
	
	<!-- Vaulters (Movement) -->
	<TechnologyLinkDefinition Name="TechnologyLinkDefinitionScienceAndExploration2To4VaultersWormholeUnique" Category="TechnologyLinkTypeCostReduction" PrerequisiteResolution="OR">
		<TechnologyPrerequisite Flags="TechnologyLinkAvailability">TechnologyLinkTo2Vaulters</TechnologyPrerequisite>
		<TechnologyPrerequisite Flags="TechnologyLinkAvailability">TechnologyWormholeVaultersCommonUnique</TechnologyPrerequisite>
		<SimulationDescriptorReference Name="TechnologyLinkScienceAndExploration2To4"/>
	</TechnologyLinkDefinition>
	<TechnologyLinkDefinition Name="TechnologyLinkDefinitionScienceAndExploration2To4VaultersWormhole" Category="TechnologyLinkTypeCostReduction" PrerequisiteResolution="OR">
		<TechnologyPrerequisite Flags="TechnologyLinkAvailability">TechnologyLinkTo2Vaulters</TechnologyPrerequisite>
		<TechnologyPrerequisite Flags="TechnologyLinkAvailability">TechnologyWormholeVaultersCommon</TechnologyPrerequisite>
		<SimulationDescriptorReference Name="TechnologyLinkScienceAndExploration2To4"/>
	</TechnologyLinkDefinition>

	<!-- Vaulters (Removing bugged/duplicate tech link) -->
	<TechnologyLinkDefinition Name="TechnologyLinkDefinitionScienceAndExploration25To6Vaulters" Category="TechnologyLinkTypeCostReduction" PrerequisiteResolution="OR">
		<SimulationDescriptorReference Name="TechnologyLinkScienceAndExploration25To6Vaulters"/>
	</TechnologyLinkDefinition>
	<TechnologyLinkDefinition Name="TechnologyLinkDefinitionScienceAndExploration25To6VaultersNoPortals" Category="TechnologyLinkTypeCostReduction" PrerequisiteResolution="OR">
		<SimulationDescriptorReference Name="TechnologyLinkScienceAndExploration25To6Vaulters"/>
	</TechnologyLinkDefinition>
	<TechnologyLinkDefinition Name="TechnologyLinkDefinitionScienceAndExploration25To6VaultersNoVaultersPopulation" Category="TechnologyLinkTypeCostReduction" PrerequisiteResolution="OR">
		<SimulationDescriptorReference Name="TechnologyLinkScienceAndExploration25To6Vaulters"/>
	</TechnologyLinkDefinition>

	<!-- Trade -->
	<TechnologyLinkDefinition Name="TechnologyLinkDefinitionEconomyAndTrade5To9" Category="TechnologyLinkTypeCostReduction" PrerequisiteResolution="OR">
		<TechnologyPrerequisite Flags="TechnologyLinkAvailability">TechnologyDust1</TechnologyPrerequisite>
		<TechnologyPrerequisite Flags="TechnologyLinkAvailability">TechnologyTrade1</TechnologyPrerequisite>
		<SimulationDescriptorReference Name="TechnologyLinkEconomyAndTrade5To9" />
	</TechnologyLinkDefinition>
	<TechnologyLinkDefinition Name="TechnologyLinkDefinitionEconomyAndTrade5To9Venetians" Category="TechnologyLinkTypeCostReduction" PrerequisiteResolution="OR">
		<TechnologyPrerequisite Flags="TechnologyLinkAvailability">TechnologyDust1</TechnologyPrerequisite>
		<TechnologyPrerequisite Flags="TechnologyLinkAvailability">TechnologyTrade1</TechnologyPrerequisite>
		<SimulationDescriptorReference Name="TechnologyLinkEconomyAndTrade5To9" />
	</TechnologyLinkDefinition>
</Datatable>
